### ISSUE TITLE
利用 Mosdns 和 AdGuardHome 搭建自己的 DNS

### ISSUE THREAD

**Issue by xukecheng** [xukecheng/gitalk-comment#3]
https://www.xukecheng.tech/use-mosdns-and-adguardhome-to-build-your-own-dns 

 国内的 DNS 服务商一般有两个，网络运营商和部分商业公司。而由于种种原因，这些 DNS 都存在或多或少的问题，这里就不细说了。而部分玩家为了尽可能地规避其中的某些问题，因此必不可少地需要自建 DNS 服务。

**Comment by vvxiang** [comment]
/ecs_tw_domain.txt /ecs_cn_domain.txt 请问这两个文件是什么样的结构，能不能自动获取到。

**Comment by xukecheng** [comment]
> @vvxiang
> /ecs_tw_domain.txt /ecs_cn_domain.txt 请问这两个文件是什么样的结构，能不能自动获取到。

这里确实忘记补充了，这个其实是来源于 [easymosdns](https://github.com/pmkol/easymosdns)，格式可以参考这个 [示例文件](https://github.com/pmkol/easymosdns/blob/main/ecs_tw_domain.txt)，我后面改下文章：
```yaml
  # 匹配强制本地解析域名的插件
  - tag: query_is_cn_domain
    type: query_matcher
    args:
      domain:
        - "provider:ecscn"

  # 匹配强制非本地解析域名的插件
  - tag: query_is_tw_domain
    type: query_matcher
    args:
      domain:
        - "provider:ecstw"
```
